create table
  public.actors (
    id bigint generated by default as identity,
    name text null,
    image_url text null,
    gender smallint null,
    biography text null,
    birthday date null,
    instagram_url text null,
    twitter_url text null,
    country_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint actors_pkey primary key (id),
    constraint actors_country_id_fkey foreign key (country_id) references countries (id)
  ) tablespace pg_default;

create table
  public.admins (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    username text null,
    name text null,
    type text null,
    password text null,
    constraint admins_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.categories (
    id bigint generated by default as identity,
    name text null,
    created_at timestamp with time zone null default now(),
    constraint categories_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.countries (
    id bigint generated by default as identity,
    name text null,
    created_at timestamp with time zone null default now(),
    constraint countries_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.directors (
    id bigint generated by default as identity,
    name text null,
    image_url text null,
    gender smallint null,
    biography text null,
    country_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint directors_pkey primary key (id),
    constraint directors_country_id_fkey foreign key (country_id) references countries (id)
  ) tablespace pg_default;

create table
  public.movie_actors (
    id bigint generated by default as identity,
    movie_id bigint null,
    actor_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint movie_actors_pkey primary key (id),
    constraint movie_actors_actor_id_fkey foreign key (actor_id) references actors (id),
    constraint movie_actors_movie_id_fkey foreign key (movie_id) references movies (id)
  ) tablespace pg_default;

create table
  public.movie_categories (
    id bigint generated by default as identity,
    movie_id bigint null,
    category_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint movie_categories_pkey primary key (id),
    constraint movie_categories_category_id_fkey foreign key (category_id) references categories (id),
    constraint movie_categories_movie_id_fkey foreign key (movie_id) references movies (id)
  ) tablespace pg_default;

create table
  public.movies (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name text null,
    description text null,
    image_url text null,
    video_url text null,
    release_date date null,
    language text null,
    status smallint null,
    director_id bigint null,
    studio_id bigint null,
    backdrop_url text null,
    constraint movies_pkey primary key (id),
    constraint movies_director_id_fkey foreign key (director_id) references directors (id),
    constraint movies_studio_id_fkey foreign key (studio_id) references studios (id)
  ) tablespace pg_default;

create table
  public.studios (
    id bigint generated by default as identity,
    name text null,
    image_url text null,
    city text null,
    country_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint studios_pkey primary key (id),
    constraint studios_country_id_fkey foreign key (country_id) references countries (id)
  ) tablespace pg_default;